<a href="https://colab.research.google.com/github/eberesquivel/colabkerastensor/blob/master/IntroNLPyNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Numpy
import numpy as np # Importing the Numpy package
a= np.array([1,4,5,8], float) # Creating Numpy array with Float variables

print(type(a)) #Type of variable

<class 'numpy.ndarray'>


In [ ]:
# Operations on the array
a[0] = 5 #Replacing the first element of the array
print(a)

[5. 4. 5. 8.]


In [ ]:
b = np.array([[1,2,3],[4,5,6]], float) # Creating a 2-D numpy array

b[0,1] # Fetching second element of 1st array

2.0

In [ ]:
print(b.shape) #Returns tuple with the shape of array

(2, 3)


In [ ]:
b.dtype #Returns the type of the value stored

dtype('float64')

In [ ]:
print(len(b)) #Returns length of the first axis

2


In [ ]:
2 in b #'in' searches for the element in the array

True

In [ ]:
0 in b


False

# Use of 'reshape' : transforms elements from 1-D to 2-D here

In [ ]:
c = np.array(range(12), float)
print(c)
print(c.shape)
print('---')
c = c.reshape((2,6)) # reshape the array in the new form
print(c)
print(c.shape)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
(12,)
---
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
(2, 6)


In [ ]:
c.fill(0) #Fills whole array with single value,done inplace
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
c.transpose() #creates transpose of the array, not done inplace

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
c.flatten() #flattens the whole array, not done inplace

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


#Concatenando 2 o mas arreglos

In [ ]:
m = np.array([1,2], float)
n = np.array([3,4,5,6], float)
p = np.concatenate((m,n))
print(p)


[1. 2. 3. 4. 5. 6.]


In [ ]:

print(p.shape)
# 'newaxis' : to increase the dimensonality of the array
q = np.array([1,2,3], float)
q[:, np.newaxis].shape


(6,)


(3, 1)

NumPy cuenta con otras funciones, como son zeros, ones, zeros_like, ones_
like, identity, eye,las cuales se usan para crear arreglos llenos de zeros y 1s, o 0s y 1s para las dimensiones asignadas.
La suma, la resta y la multiplicación ocurren en matrices del mismo tamaño.
La multiplicación en NumPy se ofrece como elemento y no como matriz
multiplicación. Si las matrices no coinciden en tamaño, la más pequeña es
repetida para realizar la operación deseada. El siguiente es un ejemplo de esto:

In [ ]:
a1 = np.array([[1,2],[3,4],[5,6]], float)
a2 = np.array([-1,3], float)
print(a1+a2)


[[0. 5.]
 [2. 7.]
 [4. 9.]]


Note pi and e are included as constants in the NumPy package.
One can refer to the following sources for detailed tutorials on NumPy:
www.numpy.org/ and https://docs.scipy.org/doc/numpy-dev/user/
quickstart.html.
NumPy offers few of the functions that are directly applicable on the
arrays: sum (summation of elements), prod (product of the elements), mean
(mean of the elements), var (variance of the elements), std (standard
deviation of the elements), argmin (index of the smallest element in array),
argmax (index of the largest element in array), sort (sort the elements),
unique (unique elements of the array).


In [ ]:
a3 = np.array([[0,2],[3,-1],[3,5]], float)
print(a3.mean(axis=0)) # Mean of elements column-wise

[2. 2.]


In [ ]:
print(a3.mean(axis=1)) # Mean of elements row-wise

[1. 1. 4.]


Note To perform the preceding operations on a multidimensional
array, include the optional argument axis in the command.
NumPy offers functions for testing the values present in the array,
such as nonzero (checks for nonzero elements), isnan (checks for “not
a number” elements), and isfinite (checks for finite elements). The
where function returns an array with the elements satisfying the following
conditions:

In [ ]:
a4 = np.array([1,3,0], float)
np.where(a!=0, 1/a ,a)

array([0.2  , 0.25 , 0.2  , 0.125])

To generate random numbers of varied length, use the random
function from NumPy.

In [ ]:
np.random.rand(2,3)


array([[0.4485339 , 0.84271217, 0.7710416 ],
       [0.89455831, 0.79791952, 0.22290105]])

Note The random number seed can be set via numpy.random.
seed (1234). NumPy uses the Mersenne Twister algorithm to
generate pseudorandom numbers.